apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5yZWRoYXQuaW8iOnsidXNlcm5hbWUiOiJyaG4tZ3BzLW1sYWNvdXJzIiwicGFzc3dvcmQiOiJPckBuZ2U5OSIsImF1dGgiOiJjbWh1TFdkd2N5MXRiR0ZqYjNWeWN6cFBja0J1WjJVNU9RPT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: rh-reg-token
type: kubernetes.io/dockerconfigjson
