---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: basic-tomcat-spaces
    file: "{{ inventory_dir }}/../.openshift/projects/projects.yml"
    action: create
- object: deployments
  content:
  - name: basic-tomcat-dev
    namespace: "{{ NAMESPACE }}"
    template: "{{ inventory_dir }}/../.openshift/deployment/template.yml"
    params: "{{ inventory_dir }}/../.openshift/deployment/dev/params"
