---
deploy_setup:
  build_project:
    NAMESPACE: redhat-cicd
    DEV_NAMESPACE: redhat-dev
  dev_project:
    NAMESPACE: redhat-dev
    NAMESPACE_DISPLAY_NAME: Redhat DEV Project
  qa_project:
    NAMESPACE: redhat-qa
    NAMESPACE_DISPLAY_NAME: Redhat QA Project

configmaps_from_files:
- name: config-env
  namespace: "{{ deploy_setup.dev_project.NAMESPACE }}"
  properties_file: "{{ WORK_DIR }}/demo/src/main/resources/appdisplay.properties"
  destination: "{{ WORK_DIR }}/demo/.openshift/files"
  maptoenv: true


openshift_cluster_content:
- galaxy_requirements: "{{ inventory_dir }}/../../.openshift/requirements.yml" 
#- object: configmaps
#  configmaps:
#  - name: config-env
#    namespace: "{{ deploy_setup.dev_project.NAMESPACE }}"
#    properties_file: "{{ WORK_DIR }}/demo/src/main/resources/appdisplay.properties"
##    destination: "{{ WORK_DIR }}/demo/.openshift/files"
#    maptoenv: true
- object: deployments 
  content:
  - name: create-config-maps
    pre_steps:
    - role: "custom-roles/roles/generate-configmaps"
      vars:
        configMaps: "{{ configmaps_from_files }}"
    namespace: "{{ deploy_setup.dev_project.NAMESPACE }}"
    file: "{{ WORK_DIR }}/demo/.openshift/files"
    tags:
    - deploy
  - name: deploy-template
    pre_steps:
    - role: "custom-roles/roles/dynamic-templates"
      vars:
         src: "{{ inventory_dir }}/../../.openshift/deployment/template.yml.j2"
         destination: "{{ inventory_dir }}/../../.openshift/deployment/template.yml"
         configMaps: "{{ configmaps_from_files }}"
    namespace: "{{ deploy_setup.dev_project.NAMESPACE }}"
    template: "{{ inventory_dir }}/../../.openshift/deployment/template.yml"
    params: "{{ inventory_dir }}/../../.openshift/deployment/dev/params"
    tags:
    - deploy
##  - name: app-config
##    namespace: "{{ NAMESPACE }}"
##    template: ".openshift/deployment/config_maps.yml"
##    params: ".openshift/deployment/dev/params"
##    tags:
##    - deploy
