---
    
openshift_cluster_content:
- object: projectrequest
  content:
  - name: basic-tomcat-spaces
    file: "{{ inventory_dir }}/../.openshift/projects/projects.yml"
    action: create
    tags:
    - deploy
- object: deployments
  content:
  - name: basic-tomcat-dev
    namespace: "{{ NAMESPACE }}"
    template: "{{ inventory_dir }}/../.openshift/deployment/template.yml"
    params: "{{ inventory_dir }}/../.openshift/deployment/dev/params"
    tags:
    - deploy
  - name: app-config
    namespace: "{{ NAMESPACE }}"
    template: ".openshift/deployment/config_maps.yml"
    params: ".openshift/deployment/dev/params"
    tags:
    - deploy
